# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'TaboolaSDKExampleSwift' do
  use_frameworks!
  
  pod 'TaboolaSDK', '~>4.0'
  pod 'MarketingCloudSDK', '= 6.4.2'
#  pod 'MarketingCloudSDK', '= 8.1.3'

  end

